version: "3"

services:
  api:
    build: packages/api
    image: chat-api
    container_name: chat-api
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  web:
    build: packages/web
    image: chat-web
    container_name: chat-web
    expose:
      - "4000"
    #environment:
    #  - API_HOST=api
    depends_on:
      - api

  db:
    image: mongo
    container_name: chat-db
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: chat
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: redis
    container_name: chat-redis
    expose:
      - "6379"
    command: ["--requirepass secret"]

  nginx:
    image: nginx
    container_name: chat-nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - web
